apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: default
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: sally94/kube-node
        ports:
          - containerPort: 3000
        volumeMounts:
        - mountPath: /project
          name: app-volume
      volumes:
      - name: app-volume
        hostPath:
          path: /home/ec2-user/AWS-EKS/backend 
