apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mongodb
spec:
  selector:
    matchLabels:
      db: mongo
  serviceName: "statefulset-mongodb"    
  replicas: 2
  template:
    metadata:
      labels:
        db: mongo
    spec:
      containers:
        - name: statefulset-mongo
          image: mongo
          ports:
            - containerPort: 27017
         